export const fallbackHeaderConfig = {
  enabled: true,
  helpDeskPhone: '+92 331 6699992',
  emergencyPhone: '+92 331 6699992',
  logo: '/assets/img/logo/logo.png',
  menuItems: [
    { id: '1', label: 'Home', link: '/', enabled: true, showOnHome: true, showOnInner: true },
    { id: '2', label: 'About', link: '/about', enabled: true, showOnHome: true, showOnInner: true },
    {
      id: '3',
      label: 'Services',
      link: '/services',
      enabled: true,
      showOnHome: true,
      showOnInner: true,
      hasDropdown: true,
      subItems: [
        { id: 's1', label: 'Medical Equipment & Devices', link: '/services/medical-equipment-devices', enabled: true },
        { id: 's2', label: 'Diagnostic & Lab Systems', link: '/services/diagnostic-lab-systems', enabled: true },
        { id: 's3', label: 'Critical Care & ICU', link: '/services/critical-care-icu', enabled: true },
        { id: 's4', label: 'Surgical Devices & OT', link: '/services/surgical-devices', enabled: true },
        { id: 's5', label: 'All Products & Services', link: '/services', enabled: true },
      ],
    },
    { id: '4', label: 'Gallery', link: '/gallery', enabled: true, showOnHome: true, showOnInner: true },
    { id: '5', label: 'Specialists', link: '/allteams', enabled: true, showOnHome: false, showOnInner: true },
    { id: '7', label: 'Blogs', link: '/blog', enabled: true, showOnHome: true, showOnInner: true },
    { id: '8', label: 'Research', link: '/research', enabled: false, showOnHome: false, showOnInner: true },
    { id: '9', label: 'Contact', link: '/contact', enabled: true, showOnHome: true, showOnInner: true },
  ],
};


export const fallbackSiteConfig = {
  header: fallbackHeaderConfig,
  hero: {
    enabled: true,
    subTitle: "Welcome to Innotech Medical Pvt Ltd",
    title: "Innovating Health Care with Advance Technologies",
    description:
      "Innotech Medical Pvt Ltd is Growing distributor of top-quality medical equipment across Pakistan At Innotech Medical, we are dedicated to bridging the gap between world-class medical innovation and Pakistan’s healthcare sector. As a leading provider of advanced biomedical technologies, diagnostic systems, and specialized clinical equipment, we empower healthcare institutions to deliver accurate diagnoses and superior patient care.",
    btn1Text: "Contact with Us",
    btn1Link: "/contact",
    btn2Text: "About us",
    btn2Link: "/about",
    videoUrl: "https://www.youtube.com/embed/d8w5SICzzxc",
    image: "/assets/img/banner/banner-01.png",
    bannerImage: "/assets/img/banner/banner-01.png",
    badge1Text: "100% Customer Satisfaction",
    badge2Text: "Help and Acess is Our Mission",
    badge3Text: "100% Quality Laboratory service",
  },
  servicesSection: {
    enabled: true,
    subTitle: "our Services",
    title: "Service Area",
    searchPlaceholder: "What are you looking for?",
  },
  about: {
    enabled: true,
    experienceYears: "7",
    experienceText: "Years of Experience",
    subTitle: "Welcome to Innotech Medical Pvt Ltd",
    title: "Innovating Healthcare with Advance Technologies",
    tagline:
      "—Empowering hospitals, diagnostic labs, and surgical suites with world-class technology and end-to-end engineering support.",
    description:
      "Innotech Medical Pvt Ltd is Established & Reputable distributor of top-quality medical equipment across Pakistan. From state-of-the-art Medical Devices and Surgical Disposable solutions to comprehensive turnkey hospital projects, our commitment goes beyond equipment distribution. We provide end-to-end technical support, regulatory compliance, and seamless integration, ensuring that healthcare providers across the nation have access to reliable, cutting-edge medical technologies.",
    imageMain: "/assets/img/about/about-bg-01.png",
    image: "/assets/img/about/about-bg-01.png",
    points: [
      "Critical Care & ICU Equipment",
      "Advanced Diagnostic & Lab Instruments",
      "Operating Room & General Medical Solutions",
      "Turnkey Projects & Technical Support",
    ],
    btn1Text: "Our HIstory",
    btn1Link: "/about",
    btn2Text: "About us",
    btn2Link: "/about",
  },
  counters: {
    enabled: true,
    item1Number: "1492",
    item1Title: "Laboratories in 100+ states",
    item2Number: "152",
    item2Title: "Laboratory specialists",
    item3Number: "1022",
    item3Title: "Material collection points",
    item4Number: "24332",
    item4Title: "Patients diagnosed in 2022",
  },
  gallerySection: {
    enabled: true,
    subTitle: "Work Gallery",
    title: "INNOTECH Gallery",
    description: "Explore our advanced medical equipment installations, diagnostic technologies, and turnkey hospital projects across Pakistan.",
    btnText: "Explore More",
    btnLink: "/gallery",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerTitle: "INNOTECH Gallery",
    bannerSubTitle: "Explore our advanced medical equipment installations, diagnostic technologies, and turnkey hospital projects across Pakistan.",
    bannerBreadcrumb: "Gallery",
    pageSectionSubTitle: "WORK GALLERY",
    pageSectionTitle: "Precision Medical & Laboratory Works",
    pageDescription: "Discover our portfolio of FDA, CE, and ISO certified biomedical device deployments, hospital turnkey setups, and laboratory automation.",
    items: [
      {
        id: 1,
        title: "COVID ANALYSIS",
        tag: "Radiologist",
        image: "/assets/img/gallery/gal-thum-01.jpg",
        link: "/services",
        enabled: true,
      },
      {
        id: 2,
        title: "Hiv Analysis & Testing",
        tag: "Anaesthetist",
        image: "/assets/img/gallery/gal-thum-02.jpg",
        link: "/services",
        enabled: true,
      },
      {
        id: 3,
        title: "Zyrtec Analysis",
        tag: "Gynaecologist",
        image: "/assets/img/gallery/gal-thum-03.jpg",
        link: "/services",
        enabled: true,
      },
      {
        id: 4,
        title: "Asthma Apply",
        tag: "Genetics",
        image: "/assets/img/gallery/gal-thum-04.jpg",
        link: "/services",
        enabled: true,
      },
      {
        id: 5,
        title: "neurological ANALYSIS",
        tag: "Forensic",
        image: "/assets/img/gallery/gal-thum-05.jpg",
        link: "/services",
        enabled: true,
      },
    ],
  },
  whyChooseUs: {
    enabled: true,
    subTitle: "Our Specialists",
    title: "Why Choose Us",
    bottomCtaText: "Scientific Research Laboratories:",
    bottomCtaLinkText: "Contact Us",
    bottomCtaLink: "/contact",
    features: [
      {
        title: "Global Standards & Quality",
        description:
          "Delivering FDA, CE, and ISO certified medical equipment from global principal brands, ensuring maximum clinical accuracy and patient safety.",
        iconClass: "flaticon-microscope",
        iconTheme: "blue",
        enabled: true,
      },
      {
        title: "Swift Turnkey Delivery",
        description:
          "Streamlined procurement and rapid installation, delivering complete healthcare projects with minimal turnaround time and total precision.",
        iconClass: "flaticon-thinking",
        iconTheme: "pink",
        enabled: true,
      },
      {
        title: "24/7 Emergency Support",
        description:
          "Round-the-clock technical coverage and rapid dispatch troubleshooting to eliminate critical equipment downtime in ICUs and OTs.",
        iconClass: "flaticon-24-hours-1",
        iconTheme: "green",
        enabled: true,
      },
      {
        title: "Certified Biomedical Experts",
        description:
          "Backed by OEM-trained engineers executing precision calibration, complex repairs, and proactive maintenance to global standards.",
        iconClass: "flaticon-team",
        iconTheme: "sky",
        enabled: true,
      },
    ],
  },
  appointment: {
    enabled: true,
    title: "GET IN TOUCH WITH US",
    emergencyText: "24/7 Emergency Service :",
    emergencyPhone: "+92 3316699992",
  },
  teamSection: {
    enabled: true,
    subTitle: "Our Team",
    title: "Meet Specialist",
  },
  testimonialSection: {
    enabled: true,
    subTitle: "Testimonial",
    title: "Customer Feedback",
  },
  brandsSection: {
    enabled: true,
    items: [
      { id: 1, image: "/assets/img/brand/brand-01.png", alt: "Brand 1", enabled: true },
      { id: 2, image: "/assets/img/brand/brand-02.png", alt: "Brand 2", enabled: true },
      { id: 3, image: "/assets/img/brand/brand-03.png", alt: "Brand 3", enabled: true },
      { id: 4, image: "/assets/img/brand/brand-04.png", alt: "Brand 4", enabled: true },
      { id: 5, image: "/assets/img/brand/brand-05.png", alt: "Brand 5", enabled: true },
      { id: 6, image: "/assets/img/brand/brand-04.png", alt: "Brand 6", enabled: true },
    ],
  },
  ctaSection: {
    enabled: true,
    title: "Looking for a best laboratory Service",
    phone: "+92 331 6699992",
  },
  blogSection: {
    enabled: true,
    subTitle: "Waht’s New",
    title: "Blog & Article",
  },
  footer: {
    enabled: true,
    description:
      "Innotech Medical Pvt Ltd is Growing distributor of top-quality medical equipment across Pakistan At Innotech Medical.",
    address:
      "1st Floor, Plot: A-301, Sardar Ali Sabri Road, Block-2, Gulshan e Iqbal, Karachi, Sindh, Pakistan.",
    phone: "+92 331 6699992",
    email: "info@innotecmedical.org",
    officeHours: "10AM - 6PM",
    weekendText: "Sat/Sund - Wekend Day",
    newsletterTitle: "Subscribe Newslatter",
    newsletterDesc:
      "Stay updated with the latest biomedical innovations, equipment releases, and healthcare technology insights across Pakistan.",
    copyrightText:
      "© Copyright ©2026 - 2027 INNOTECH MEDICAL Pvt Ltd. All Rights Reserved",
    socialLinks: {
      facebook: "https://facebook.com/innotechmedical",
      twitter: "https://twitter.com/innotechmedical",
      linkedin: "https://linkedin.com/company/innotech-medical",
      instagram: "",
      youtube: "",
      skype: "",
    },
  },
  generalSettings: {
    siteName: "INNOTECH MEDICAL PVT LTD",
    siteTagline: "Innovating Healthcare with Advance Technologies",
    mainLogo: "/assets/img/logo/logo.png",
    whiteLogo: "/assets/img/logo/white-logo.png",
    favicon: "/assets/img/logo/favicon.png",
    adminName: "INNOTECH Admin Portal",
    adminLogo: "/assets/img/logo/white-logo.png",
  },
  seoSettings: {
    metaTitle: "INNOTECH MEDICAL PVT LTD - Innovating Healthcare with Advance Technologies",
    metaDescription:
      "Innotech Medical Pvt Ltd is a leading distributor of top-quality medical equipment, diagnostic systems, and specialized clinical solutions across Pakistan.",
    metaKeywords:
      "medical equipment, diagnostic systems, laboratory supplies, hospital devices, Innotech Medical, Pakistan healthcare, turnkey hospital projects, biomedical engineering",
    metaAuthor: "Innotech Medical Pvt Ltd",
    metaImage: "/assets/img/banner/breadcrumb-01.jpg",
    canonicalUrl: "https://innotechmedical.org",
    googleAnalyticsId: "",
    robotsIndex: "index, follow",
  },
  chatWidget: {
    enabled: true,
    title: "Innotech Live Support",
    subtitle: "Typically replies within minutes",
    welcomeMessage: "Welcome to Innotech Medical Support! How can we assist you with our medical equipment and services today?",
    autoReplyEnabled: true,
    autoReplyMessage: "Thank you for reaching out! Our support team has received your message and will respond to you shortly. For urgent assistance, please call +92 331 6699992.",
    agentName: "Innotech Support Team",
    agentAvatar: "/assets/img/logo/favicon.png",
  },
  whatsappWidget: {
    enabled: true,
    phoneNumber: "+92 331 6699992",
    defaultMessage: "Hello Innotech Medical, I would like to inquire about your medical equipment and solutions.",
    tooltipText: "Chat with us on WhatsApp",
  },
};


export const fallbackServices = [
  {
    _id: "srv-1",
    title: "HEMOGLOBIN TEST & HEMATOLOGY",
    slug: "hemoglobin-test",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-hemoglobin-test-meter",
    iconTheme: "blue",
    description:
      "Precision hemoglobin and hematocrit analysis equipment delivering rapid, lab-accurate diagnostic measurements.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Automated Clinical Diagnostic & Hematology Systems",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Hemoglobin & Hematology Analytical Process",
    processText:
      "Innotech Medical supplies automated multi-parameter hematology analyzers that provide rapid, dependable complete blood count (CBC) profiles and accurate hemoglobin diagnostics for modern clinical laboratories and hospital pathology departments across Pakistan.",
    processPoints: [
      "Precision microfluidic measurement channels with laser optical flow cytometry.",
      "High-throughput automated sampling with closed-tube barcode scanning.",
      "Fully compliant with ISO 15189 laboratory quality standards.",
      "Comprehensive warranty, preventive calibration, and genuine reagent packs.",
    ],
    stepsTitle: "4 Simple Diagnostic & Calibration Steps",
    stepsText:
      "Our turnkey analytical process guarantees maximum instrument uptime, precision calibration benchmarks, and seamless hospital LIS (Laboratory Information System) integration.",
    stepPoints1: ["Sample Preparation & Barcode Scan", "Microfluidic Analysis", "Automated Quality Control"],
    stepPoints2: ["High-Resolution Optical Detection", "Digital Differential Profiling", "Real-Time LIS Sync"],
    stepPoints3: ["Automated Probe Washing", "Diagnostic Report Generation", "Preventive Maintenance Log"],
    specsTable: [
      { feature: "Throughput", spec: "Up to 60 - 120 samples per hour" },
      { feature: "Sample Volume", spec: "15 µL - 20 µL whole blood" },
      { feature: "Parameters", spec: "24+ Reportable Diagnostic Parameters" },
      { feature: "Display", spec: "10.4-inch High-Resolution Color Touchscreen" },
      { feature: "Connectivity", spec: "Ethernet, USB, RS-232, Bi-directional LIS" },
    ],
    fullContent:
      "<p>Our advanced hematology analyzers combine patented optical counting with impedance measurement to deliver gold-standard hematocrit, platelet, and leukocyte evaluations with sub-minute turnaround times.</p>",
    enabled: true,
    showInHeader: true,
  },
  {
    _id: "srv-2",
    title: "MEDICAL EQUIPMENT & DEVICES",
    slug: "medical-equipment-devices",
    category: "Critical Care & ICU",
    iconClass: "flaticon-blood-test",
    iconTheme: "pink",
    description:
      "High-performance clinical equipment, ICU monitors, ventilators, and emergency patient resuscitation systems.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Advanced ICU, Emergency & Clinical Life Support Technologies",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Clinical Engineering & Intensive Care Infrastructure",
    processText:
      "Innotech Medical delivers state-of-the-art medical devices and life-support platforms engineered for high-acuity healthcare environments. From intensive care ventilators to modular multi-parameter patient monitoring suites, our equipment empowers healthcare providers with real-time biometric analytics.",
    processPoints: [
      "FDA and CE certified patient monitors with high-resolution arrhythmia detection.",
      "Invasive and non-invasive intensive care ventilators with smart weaning modes.",
      "Integrated emergency resuscitation defibrillators with CPR feedback algorithms.",
      "24/7 biomedical emergency hotline and certified on-site maintenance engineers.",
    ],
    stepsTitle: "4 Simple Deployment & Support Steps",
    stepsText:
      "We partner closely with clinical directors, biomedical teams, and hospital administrators to deliver end-to-end turnkey installation, validation, and clinical training.",
    stepPoints1: ["Hospital Site Audit & Assessment", "Power & Gas Supply Compatibility", "Biomedical Engineering Review"],
    stepPoints2: ["Turnkey Delivery & Assembly", "Electrical Safety & Gas Leak Testing", "Digital Monitoring Network Setup"],
    stepPoints3: ["Physician & Nurse Operational Training", "Preventive Maintenance Calibration", "24/7 Rapid Emergency Response"],
    specsTable: [
      { feature: "Certification", spec: "FDA 510(k), CE Mark, ISO 13485" },
      { feature: "Battery Backup", spec: "Integrated Lithium-Ion (Up to 6 Hours)" },
      { feature: "Data Connectivity", spec: "HL7, DICOM, Wi-Fi, Central Monitoring Station" },
      { feature: "Alarms", spec: "Visual 360-degree LED & Audible Multi-Level Warnings" },
    ],
    fullContent:
      "<p>Engineered for continuous 24/7 operation in high-demand ICUs, CCUs, and Emergency Departments. All devices feature modular plug-and-play expansions and intuitive touch interfaces.</p>",
    enabled: true,
    showInHeader: true,
  },
  {
    _id: "srv-3",
    title: "DIAGNOSTIC & LAB SYSTEMS",
    slug: "diagnostic-lab-systems",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-biochemistry",
    iconTheme: "green",
    description:
      "State-of-the-art clinical chemistry analyzers ensuring rigorous biochemical profiling and dependable assay performance.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Automated Clinical Chemistry & Immunoassay Platforms",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "High-Throughput Clinical Chemistry Automation",
    processText:
      "Equip your laboratory with next-generation biochemistry and immunoassay analyzers. Our diagnostic solutions offer unmatched photometric accuracy, low reagent consumption, and intuitive quality control software.",
    processPoints: [
      "Discrete, random access, fully automated biochemistry systems.",
      "Advanced holographic concave flat field grating optics with sub-nanometer accuracy.",
      "Clot detection, liquid level monitoring, and vertical & horizontal collision protection.",
      "Direct refrigeration system for reagent trays ensuring extended reagent stability.",
    ],
    stepsTitle: "4 Simple Laboratory Workflow Steps",
    stepsText:
      "Our clinical lab specialists ensure seamless installation, workflow optimization, and continuous supply of premium diagnostic reagents across Pakistan.",
    stepPoints1: ["Laboratory Space & Power Preparation", "Water Purification Integration", "Analyzer Assembly & Leveling"],
    stepPoints2: ["Reagent & Calibrator Loading", "Photometric Alignment & Calibration", "Multi-Level Control Verification"],
    stepPoints3: ["LIS Bi-Directional Handshake", "Lab Technician Hands-On Training", "Scheduled Preventative Service"],
    specsTable: [
      { feature: "Throughput", spec: "400 - 800 photometric tests/hour" },
      { feature: "Reagent Positions", spec: "80 refrigerated positions" },
      { feature: "Sample Positions", spec: "100 positions (including STAT)" },
      { feature: "Reaction Volume", spec: "100 µL minimum reaction volume" },
    ],
    fullContent:
      "<p>Optimized for government hospitals, commercial diagnostic networks, and private reference labs seeking maximum analytical reliability with minimal operating costs.</p>",
    enabled: true,
    showInHeader: true,
  },
  {
    _id: "srv-4",
    title: "CRITICAL CARE & ICU",
    slug: "critical-care-icu",
    category: "Critical Care & ICU",
    iconClass: "flaticon-dna",
    iconTheme: "pink",
    description:
      "Comprehensive ICU patient monitoring systems, advanced ventilators, and critical life-support medical instrumentation.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Intensive Care, Neonatal & High-Dependency Unit Solutions",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Continuous Biometric Monitoring & Life Support",
    processText:
      "Innotech Medical provides comprehensive intensive care suites comprising advanced mechanical ventilators, infusion pumps, syringe drivers, and multi-parameter central monitoring stations.",
    processPoints: [
      "High-precision tidal volume delivery down to 2 mL for neonatal applications.",
      "Continuous cardiac output, EtCO2, BIS, and invasive hemodynamic monitoring.",
      "Seamless central station networking supporting up to 64 beds simultaneously.",
      "Certified bio-medical engineering team offering 24/7 technical hotline.",
    ],
    stepsTitle: "4 Simple Critical Care Steps",
    stepsText:
      "Our certified biomedical engineers perform end-to-end installation, gas line calibration, and ICU staff training.",
    stepPoints1: ["ICU Gas & Electrical Verification", "Life-Support Equipment Mounting", "Sensor & Cable Integrity Check"],
    stepPoints2: ["Pneumatic Flow Calibration", "Central Station Telemetry Sync", "Clinical Alarm Configuration"],
    stepPoints3: ["Medical Staff In-Service Training", "Safety Compliance Certification", "Quarterly Preventive Maintenance"],
    specsTable: [
      { feature: "Ventilation Modes", spec: "VCV, PCV, SIMV, PSV, PRVC, APRV, BiLevel" },
      { feature: "Display", spec: "15-inch Touchscreen with Waveform Loops" },
      { feature: "Gas Supply", spec: "Oxygen & Air Pipeline (2.8 - 6.0 bar)" },
    ],
    fullContent:
      "<p>Designed for demanding intensive care scenarios where uninterrupted operation and crystal-clear clinical visibility are paramount.</p>",
    enabled: true,
    showInHeader: true,
  },
  {
    _id: "srv-5",
    title: "SURGICAL DEVICES & OT",
    slug: "surgical-devices",
    category: "Surgical & OT",
    iconClass: "flaticon-dna-1",
    iconTheme: "green",
    description:
      "Ergonomic operating theatre equipment, surgical disposables, electrosurgical units, and sterile surgical technologies.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Operating Theatre Suites, Surgical Lights & Electrosurgery",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Operating Room Architecture & Surgical Precision",
    processText:
      "From hydraulic and electro-hydraulic operating tables to shadowless LED surgical lights and advanced electro-cautery generators, Innotech Medical equips modern operating theatres with ergonomic, sterile, and reliable technologies.",
    processPoints: [
      "High-definition surgical lighting with color temperature adjustment (Ra > 97).",
      "Multi-position surgical tables with carbon fiber radiolucent table tops for C-Arm imaging.",
      "Smart electrosurgical units with bipolar vessel sealing and auto-cut modes.",
      "Surgical disposable packs, sterile drapes, and high-tensile suture materials.",
    ],
    stepsTitle: "4 Simple OT Commissioning Steps",
    stepsText:
      "We ensure operating room equipment meets sterile compliance, laminar flow integration, and electrical safety standards.",
    stepPoints1: ["Ceiling Structure & Arm Load Testing", "Electrical Isolation & Grounding", "Surgical Table Positioning"],
    stepPoints2: ["LED Optical Illumination Field Test", "Electrosurgical HF Leakage Verification", "Surgeon Ergonomics Setup"],
    stepPoints3: ["Sterilization Protocol Verification", "Surgical Team Operational Training", "Preventive Maintenance SLA"],
    specsTable: [
      { feature: "Light Intensity", spec: "Up to 160,000 Lux shadowless illumination" },
      { feature: "Table Weight Capacity", spec: "Up to 350 kg safe working load" },
      { feature: "Generator Power", spec: "400W Monopolar / 150W Bipolar with Vessel Sealing" },
    ],
    fullContent:
      "<p>Complete turnkey operating room solutions designed to maximize surgical precision, minimize infection risks, and enhance surgeon comfort.</p>",
    enabled: true,
    showInHeader: true,
  },
  {
    _id: "srv-6",
    title: "DIAGNOSTIC IMAGING",
    slug: "diagnostic-imaging",
    category: "Imaging & Radiology",
    iconClass: "flaticon-microscope-1",
    iconTheme: "blue",
    description:
      "High-resolution ultrasound scanners, digital radiography systems, and precision clinical diagnostic visualization.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Ultrasound Scanners & Digital Radiography Systems",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "High-Resolution Diagnostic Imaging Solutions",
    processText:
      "Innotech Medical delivers state-of-the-art color Doppler ultrasound machines, portable ultrasound units, and digital radiography systems that empower radiologists with crystal-clear anatomical resolution and advanced measurement packages.",
    processPoints: [
      "Advanced single-crystal probe technology for exceptional penetration and detail.",
      "Automated Doppler measurement packages for Cardiology, OB/GYN, and Vascular.",
      "DICOM 3.0 compliant for seamless PACS archiving and teleradiology.",
      "Comprehensive probe protection and warranty coverage across Pakistan.",
    ],
    stepsTitle: "4 Simple Installation Steps",
    stepsText:
      "Our imaging application specialists provide on-site configuration, DICOM PACS integration, and physician training.",
    stepPoints1: ["System Delivery & Probe Inspection", "DICOM / PACS Network Configuration", "Image Preset Customization"],
    stepPoints2: ["Phantom Resolution & Artifact Testing", "Color Doppler Sensitivity Tuning", "Patient Database Setup"],
    specsTable: [
      { feature: "Display", spec: "21.5-inch High-Definition LED Monitor + Touch Panel" },
      { feature: "Transducers", spec: "Convex, Linear, Phased Array, Endocavity, 4D Volume" },
      { feature: "Imaging Modes", spec: "B, M, Color Doppler, Power Doppler, PW, CW, Elastography" },
    ],
    fullContent:
      "<p>Delivering exceptional diagnostic clarity for hospitals, imaging centers, and private clinical practices across Pakistan.</p>",
    enabled: true,
    showInHeader: false,
  },
  {
    _id: "srv-7",
    title: "BLOOD TESTING & ANALYSIS",
    slug: "blood-testing",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-blood-test",
    iconTheme: "pink",
    description:
      "Advanced clinical blood analysis platforms for comprehensive coagulation, biochemistry, and immunodiagnostic testing.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Automated Clinical Blood Analysis & Laboratory Diagnostics",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Blood Testing & Diagnostic Workflow Process",
    processText:
      "Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system, and sed expounds the actual teachings of that greater truth. Innotech Medical equips pathology centers with robust, automated blood analysis systems guaranteeing high accuracy and rapid throughput.",
    processPoints: [
      "Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.",
      "Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque.",
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis.",
      "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.",
    ],
    stepsTitle: "4 Simple Steps",
    stepsText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    stepPoints1: ["Extramural Funding", "Bacteria Markers", "Nam nec mi euismod", "In aliquet dui nec lectus"],
    stepPoints2: ["Sample Preparation", "Optical Detection", "Quality Control Verification", "Automated Calibration"],
    stepPoints3: ["LIS Data Sync", "Report Validation", "Digital Archiving", "Preventive Maintenance"],
    specsTable: [
      { feature: "Throughput", spec: "Up to 120 tests / hour" },
      { feature: "Sample Volume", spec: "10 µL - 25 µL Whole Blood" },
      { feature: "Parameters", spec: "Complete 5-Part Differential Diagnostics" },
      { feature: "Quality Control", spec: "Automated L-J Graph Multi-Level Control" },
    ],
    fullContent:
      "<p>Equipped with intelligent clot detection and sample level sensors to prevent sampling errors. Features bi-directional LIS integration for automated electronic medical record updates.</p>",
    enabled: true,
    showInHeader: false,
  },
  {
    _id: "srv-8",
    title: "BIOCHEMISTRY ANALYSIS",
    slug: "biochemistry",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-biochemistry",
    iconTheme: "green",
    description:
      "High-throughput automated clinical chemistry analyzers delivering accurate lipid, enzyme, electrolyte, and metabolic profiles.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Advanced Clinical Biochemistry & Immunoassay Systems",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Biochemistry Analytical Process",
    processText:
      "Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a completed account of the system. Our clinical chemistry systems offer unmatched photometric precision and low reagent consumption.",
    processPoints: [
      "Discrete, random access, fully automated biochemistry systems.",
      "Holographic concave flat field grating optics with sub-nanometer accuracy.",
      "Direct refrigeration system for reagent trays ensuring extended reagent stability.",
      "Automated probe washing with carry-over less than 0.05%.",
    ],
    stepsTitle: "4 Simple Steps",
    stepsText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto.",
    stepPoints1: ["Extramural Funding", "Bacteria Markers", "Nam nec mi euismod", "In aliquet dui nec lectus"],
    stepPoints2: ["Reagent Loading", "Photometric Calibration", "STAT Sample Prioritization", "Automated Dilution"],
    stepPoints3: ["LIS Data Sync", "Report Generation", "Diagnostic Verification", "Scheduled Maintenance"],
    specsTable: [
      { feature: "Throughput", spec: "400 - 800 photometric tests/hour" },
      { feature: "Reagent Positions", spec: "80 refrigerated positions" },
      { feature: "Sample Positions", spec: "100 positions with barcode reader" },
      { feature: "Reaction Volume", spec: "100 µL minimum reaction volume" },
    ],
    fullContent:
      "<p>Engineered for private reference laboratories, hospital networks, and diagnostic centers requiring maximum analytical precision with minimum cost per test.</p>",
    enabled: true,
    showInHeader: false,
  },
  {
    _id: "srv-9",
    title: "HISTOPATHOLOGY",
    slug: "histopatology",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-dna-1",
    iconTheme: "sky",
    description:
      "Precision tissue processors, microtomes, slide stainers, and histology equipment for cellular diagnostic pathology.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Comprehensive Histology, Cytology & Tissue Processing Systems",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Histopathology Tissue Examination Process",
    processText:
      "Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Innotech Medical supplies automated tissue processors and rotary microtomes for clinical pathology laboratories.",
    processPoints: [
      "Precision rotary microtomes with micrometric sectioning thickness control.",
      "Automated vacuum tissue processors with enclosed fume control systems.",
      "High-throughput automated slide stainers and coverslippers.",
      "Cryostats for rapid intraoperative frozen section diagnostics.",
    ],
    stepsTitle: "4 Simple Steps",
    stepsText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.",
    stepPoints1: ["Tissue Fixation", "Dehydration & Clearing", "Paraffin Embedding", "Precision Microtomy"],
    stepPoints2: ["Slide Mounting", "Automated H&E Staining", "Coverslipping", "Quality Inspection"],
    stepPoints3: ["Digital Slide Scanning", "Pathologist Review", "Diagnostic Reporting", "Specimen Archiving"],
    specsTable: [
      { feature: "Section Thickness Range", spec: "0.5 µm - 100 µm" },
      { feature: "Specimen Feed", spec: "Motorized & Manual Dual Operation" },
      { feature: "Retraction Range", spec: "5 - 100 µm adjustable" },
      { feature: "Blade Compatibility", spec: "High & Low Profile Disposable Blades" },
    ],
    fullContent:
      "<p>Ensure flawless tissue ribbons and distortion-free biopsies for accurate oncological and surgical pathology assessments.</p>",
    enabled: true,
    showInHeader: false,
  },
  {
    _id: "srv-10",
    title: "MICROBIOLOGY",
    slug: "microbiology",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-bacteria",
    iconTheme: "default",
    description:
      "Automated microbial identification, antibiotic susceptibility testing (AST), and blood culture instrumentation.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Automated Microbial Identification & Susceptibility Testing",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Microbiology Identification & AST Process",
    processText:
      "Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Accelerate organism identification and antimicrobial susceptibility reporting with advanced automated platforms.",
    processPoints: [
      "Rapid microbial identification for Gram-negative, Gram-positive, and fungal pathogens.",
      "Automated minimum inhibitory concentration (MIC) determination.",
      "Continuous-monitoring blood culture incubation systems.",
      "Full compliance with EUCAST and CLSI antimicrobial testing guidelines.",
    ],
    stepsTitle: "4 Simple Steps",
    stepsText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.",
    stepPoints1: ["Inoculation & Incubation", "Bacterial Isolation", "ID Card Setup", "Continuous Optical Reading"],
    stepPoints2: ["Phenotypic Analysis", "Expert System Rule Check", "MIC Validation", "Resistance Flagging"],
    stepPoints3: ["LIS Real-Time Sync", "Critical Result Notification", "Epidemiology Tracking", "Sterilization Control"],
    specsTable: [
      { feature: "Capacity", spec: "64 - 120 test cards simultaneously" },
      { feature: "Time to Result", spec: "Rapid identification in 5 - 8 hours" },
      { feature: "Database", spec: "Over 500+ clinically relevant microorganisms" },
      { feature: "Incubation Temp", spec: "35°C - 37°C ± 0.5°C precise control" },
    ],
    fullContent:
      "<p>Combat antimicrobial resistance and guide targeted antibiotic therapy with rapid, standardized microbial diagnostic systems.</p>",
    enabled: true,
    showInHeader: false,
  },
  {
    _id: "srv-11",
    title: "GENETICS & MOLECULAR DIAGNOSTICS",
    slug: "genetics",
    category: "Diagnostic & Lab Systems",
    iconClass: "flaticon-dna",
    iconTheme: "pink",
    description:
      "Real-time PCR thermal cyclers, nucleic acid extraction systems, and molecular genetic diagnostic platforms.",
    bannerImage: "/assets/img/banner/breadcrumb-01.jpg",
    bannerSubTitle: "Advanced Molecular Diagnostics, PCR & Genetic Analysis",
    image1: "/assets/img/services/services-thumb-07.jpg",
    image2: "/assets/img/services/services-thumb-08.jpg",
    showcaseBanner: "/assets/img/services/services-thumb-09.jpg",
    processTitle: "Genetic & Molecular Diagnostic Process",
    processText:
      "Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Our real-time PCR platforms deliver sub-single-copy sensitivity for infectious diseases, oncology, and genetic mutations.",
    processPoints: [
      "Multi-channel optical fluorescence detection (FAM, VIC, ROX, CY5, etc.).",
      "Automated high-speed magnetic bead nucleic acid extraction.",
      "Precision peltier thermal blocks with rapid ramp rates up to 6.5°C/sec.",
      "Intuitive software with absolute quantification and melting curve analysis.",
    ],
    stepsTitle: "4 Simple Steps",
    stepsText:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.",
    stepPoints1: ["Automated DNA/RNA Extraction", "PCR Master Mix Preparation", "Optical Plate Loading", "Thermal Cycling Run"],
    stepPoints2: ["Fluorescence Signal Acquisition", "Threshold Baseline Calculation", "Amplification Curve Review", "Gene Mutation Check"],
    stepPoints3: ["Quality Control Approval", "Diagnostic Report Export", "LIS Integration", "Instrument Decontamination"],
    specsTable: [
      { feature: "Sample Capacity", spec: "96-well 0.2 mL PCR plate / 8-strip tubes" },
      { feature: "Detection Channels", spec: "4 to 6 optical detection channels" },
      { feature: "Ramping Rate", spec: "Up to 6.5°C / second" },
      { feature: "Dynamic Range", spec: "1 - 10^10 copies / reaction" },
    ],
    fullContent:
      "<p>Gold-standard real-time qPCR amplification for viral load quantification, mutation analysis, and hereditary genetic diagnostics.</p>",
    enabled: true,
    showInHeader: false,
  },
];


export const fallbackGallery = [
  {
    id: 1,
    title: "COVID ANALYSIS",
    tag: "Radiologist",
    image: "/assets/img/gallery/gal-thum-01.jpg",
    link: "/services",
    enabled: true,
  },
  {
    id: 2,
    title: "Hiv Analysis & Testing",
    tag: "Anaesthetist",
    image: "/assets/img/gallery/gal-thum-02.jpg",
    link: "/services",
    enabled: true,
  },
  {
    id: 3,
    title: "Zyrtec Analysis",
    tag: "Gynaecologist",
    image: "/assets/img/gallery/gal-thum-03.jpg",
    link: "/services",
    enabled: true,
  },
  {
    id: 4,
    title: "Asthma Apply",
    tag: "Genetics",
    image: "/assets/img/gallery/gal-thum-04.jpg",
    link: "/services",
    enabled: true,
  },
  {
    id: 5,
    title: "neurological ANALYSIS",
    tag: "Forensic",
    image: "/assets/img/gallery/gal-thum-05.jpg",
    link: "/services",
    enabled: true,
  },
];

export const fallbackTeam = [
  {
    _id: "team-1",
    name: "Cameron Williamson",
    position: "Genetic Specialist",
    bio: "Providing insight-driven transformation to investment banks, wealth and asset mana, exchanges, Finance",
    image: "/assets/img/team/team-thumb-01.jpg",
    socialLinks: { youtube: "#", twitter: "#", facebook: "#", skype: "#" },
    enabled: true,
  },
  {
    _id: "team-2",
    name: "Savannah Nguyen",
    position: "Anaesthetist Specialist",
    bio: "Providing insight-driven transformation to investment banks, wealth and asset mana, exchanges, Finance",
    image: "/assets/img/team/team-thumb-02.jpg",
    socialLinks: { youtube: "#", twitter: "#", facebook: "#", skype: "#" },
    enabled: true,
  },
  {
    _id: "team-3",
    name: "Darlene Robertson",
    position: "Gynaecologist Specialist",
    bio: "Providing insight-driven transformation to investment banks, wealth and asset mana, exchanges, Finance",
    image: "/assets/img/team/team-thumb-03.jpg",
    socialLinks: { youtube: "#", twitter: "#", facebook: "#", skype: "#" },
    enabled: true,
  },
  {
    _id: "team-4",
    name: "Jhon Methweu",
    position: "Radiologist Specialist",
    bio: "Providing insight-driven transformation to investment banks, wealth and asset mana, exchanges, Finance",
    image: "/assets/img/team/team-thumb-04.jpg",
    socialLinks: { youtube: "#", twitter: "#", facebook: "#", skype: "#" },
    enabled: true,
  },
];

export const fallbackTestimonials = [
  {
    _id: "testi-1",
    name: "Darlene Robertson",
    position: "Secretary of (FlaxStudio)",
    review:
      "BIoxlab is another theme that is beautiful and professinally constructed by the Developers. The price for the template is checp but not qualityh of product.what a bargain , This theme works for many types of web sites and seems to be durble dows nt break and it.",
    avatar: "/assets/img/icon/testi-ava-01.jpg",
    enabled: true,
  },
  {
    _id: "testi-2",
    name: "Courtney Henry",
    position: "CEO of (FlaxStudio)",
    review:
      "BIoxlab is another theme that is beautiful and professinally constructed by the Developers. The price for the template is checp but not qualityh of product.what a bargain , This theme works for many types of web sites and seems to be durble dows nt break and it.",
    avatar: "/assets/img/icon/testi-ava-02.jpg",
    enabled: true,
  },
  {
    _id: "testi-3",
    name: "Kathryn Murphy",
    position: "Manager of (FlaxStudio)",
    review:
      "BIoxlab is another theme that is beautiful and professinally constructed by the Developers. The price for the template is checp but not qualityh of product.what a bargain , This theme works for many types of web sites and seems to be durble dows nt break and it.",
    avatar: "/assets/img/icon/testi-ava-03.jpg",
    enabled: true,
  },
  {
    _id: "testi-4",
    name: "Darlene Robertson",
    position: "Programmer of (FlaxStudio)",
    review:
      "BIoxlab is another theme that is beautiful and professinally constructed by the Developers. The price for the template is checp but not qualityh of product.what a bargain , This theme works for many types of web sites and seems to be durble dows nt break and it.",
    avatar: "/assets/img/icon/testi-ava-07.png",
    enabled: true,
  },
];

export const fallbackBlogs = [
  {
    _id: "blog-1",
    title: "Heart Diseases Tests Ordered By Doctors",
    slug: "heart-diseases-tests-ordered-by-doctors",
    category: "Medicine",
    dateDay: "26",
    dateMonth: "Dec",
    excerpt: "Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla ...",
    image: "/assets/img/blog/blog-thumb-01.jpg",
    enabled: true,
  },
  {
    _id: "blog-2",
    title: "Heart Diseases Tests Ordered By Doctors",
    slug: "heart-diseases-tests-ordered-by-doctors-2",
    category: "Medicine",
    dateDay: "26",
    dateMonth: "Dec",
    excerpt: "Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla ...",
    image: "/assets/img/blog/blog-thumb-02.jpg",
    enabled: true,
  },
  {
    _id: "blog-3",
    title: "Identifying bases of disease pathophysio",
    slug: "identifying-bases-of-disease-pathophysio",
    category: "Medicine",
    dateDay: "26",
    dateMonth: "Dec",
    excerpt: "Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla ...",
    image: "/assets/img/blog/blog-thumb-03.jpg",
    enabled: true,
  },
  {
    _id: "blog-4",
    title: "Coronavirus global health emergency",
    slug: "coronavirus-global-health-emergency",
    category: "Medicine",
    dateDay: "26",
    dateMonth: "Dec",
    excerpt: "Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla ...",
    image: "/assets/img/blog/blog-thumb-04.jpg",
    enabled: true,
  },
];

export const fallbackBrands = [
  { id: 1, image: "/assets/img/brand/brand-01.png", alt: "Brand 1", enabled: true },
  { id: 2, image: "/assets/img/brand/brand-02.png", alt: "Brand 2", enabled: true },
  { id: 3, image: "/assets/img/brand/brand-03.png", alt: "Brand 3", enabled: true },
  { id: 4, image: "/assets/img/brand/brand-04.png", alt: "Brand 4", enabled: true },
  { id: 5, image: "/assets/img/brand/brand-05.png", alt: "Brand 5", enabled: true },
  { id: 6, image: "/assets/img/brand/brand-04.png", alt: "Brand 6", enabled: true },
];

export const fallbackAboutPage = {
  banner: {
    enabled: true,
    title: 'About us',
    subTitle: '',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  about: {
    enabled: true,
    experienceYears: '7',
    experienceText: 'Years of Experience',
    title: 'Innovating Healthcare with Advance Technologies',
    linkText: 'Read our MIssion & Vission',
    linkUrl: '#process-mission-tabs',
    description: `At Innotech Medical, we are dedicated to bridging the gap between world-class medical innovation and Pakistan’s healthcare sector. As a leading provider of advanced biomedical technologies, diagnostic systems, and specialized clinical equipment, we empower healthcare institutions to deliver accurate diagnoses and superior patient care.

From state-of-the-art imaging and laboratory solutions to comprehensive turnkey hospital projects, our commitment goes beyond equipment distribution. We provide end-to-end technical support, regulatory compliance, and seamless integration, ensuring that healthcare providers across the nation have access to reliable, cutting-edge medical technologies.`,
    imageMain: '/assets/img/about/about-bg-04.jpg',
    shape1: '/assets/img/about/about-bg-05.jpg',
    shape2: '/assets/img/about/about-bg-06.jpg',
  },
  counters: {
    enabled: true,
    item1Number: '1492',
    item1Title: 'Laboratories in 100+ states',
    item2Number: '152',
    item2Title: 'Laboratory specialists',
    item3Number: '1022',
    item3Title: 'Material collection points',
    item4Number: '24332',
    item4Title: 'Patients diagnosed in 2022',
  },
  whyChooseUs: fallbackSiteConfig.whyChooseUs,
  tabsSection: {
    enabled: true,
    processTitle: 'Our Process',
    processInfo: 'Your trusted partner for medical equipment procurement, turnkey installations,\nand technical integration across Pakistan.',
    step1Title: 'Consultation & Proposal',
    step1Desc: 'Understanding facility requirements to recommend compliant, cost-effective medical equipment solutions.',
    step2Title: 'Seamless Deployment',
    step2Desc: 'Rapid procurement, physical installation, and precise site calibration by certified biomedical engineers.',
    step3Title: 'Integration & Support',
    step3Desc: 'Comprehensive staff application training alongside 24/7 technical support and routine maintenance.',
    missionTitle: 'Our Mission',
    missionInfo: 'Your full service lab for clinical trials. Our process is to ensure the generation of \naccurate and precise findings',
    missionHeadline: 'Our Mission is Give You Always Best Results.',
    missionDesc: 'To enhance the quality of healthcare across Pakistan by delivering state-of-the-art medical devices, advanced diagnostic technologies, and uncompromised technical support to hospitals and laboratories.',
    missionImage1: '/assets/img/tab/tab-thumb-03.jpg',
    missionImage2: '/assets/img/tab/tab-thumb-04.jpg',
    valueTitle: 'Our Value',
    valueInfo: 'Your full service lab for clinical trials. Our process is to ensure the generation of \naccurate and precise findings',
    valueHeadline: 'We are Trusted by over 25000+ of customers',
    valueDesc: 'To become Pakistan’s premier and most trusted B2B healthcare partner, driving innovation in biomedical engineering and empowering institutions with futuristic medical solutions.',
    valueImage1: '/assets/img/tab/tab-thumb-01.jpg',
    valueImage2: '/assets/img/tab/tab-thumb-02.jpg',
  },
  teamSection: {
    enabled: true,
    subTitle: 'Our Team',
    title: 'Meet Specialist',
  },
};

export const fallbackContactPage = {
  banner: {
    enabled: true,
    title: 'Contact Us',
    subTitle: 'Get in Touch with Innotech Medical Pvt Ltd',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  info: {
    enabled: true,
    phoneTitle: '24/7 Emergency Line',
    phone: '+92 331 6699992',
    phoneSub: 'Rapid Technical & Clinical Dispatch',
    emailTitle: 'Official Email',
    email: 'info@innotecmedical.org',
    emailSub: 'Quick Response within 24 Hours',
    addressTitle: 'Head Office Address',
    address: '1st Floor, Plot: A-301, Sardar Ali Sabri Road, Block-2, Gulshan e Iqbal, Karachi, Sindh, Pakistan.',
    officeHoursTitle: 'Working Hours',
    officeHours: 'Monday - Saturday: 10:00 AM - 6:00 PM',
    weekendText: 'Sunday: Emergency On-Call Technical Support',
  },
  formSection: {
    enabled: true,
    subTitle: 'SEND US AN INQUIRY',
    title: 'Ready to Upgrade Your Hospital or Laboratory?',
    description:
      'Leave your project requirements, equipment inquiries, or technical support requests below. Our biomedical specialists will assist you immediately.',
    emergencyText: '24/7 Direct Line :',
    emergencyPhone: '+92 331 6699992',
  },
  map: {
    enabled: true,
    mapUrl:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3618.398687235284!2d67.09458927599554!3d24.91849894292107!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33f32486715f5%3A0xc39eb9f886fdf40!2sGulshan-e-Iqbal%2C%20Karachi!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s',
  },
};

export const fallbackTermsPage = {
  banner: {
    enabled: true,
    title: 'Terms & Conditions',
    subTitle: 'Legal Terms & Healthcare Equipment Procurement Agreement',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  lastUpdated: 'August 15, 2026',
  companyName: 'Innotech Medical Pvt Ltd',
  introduction:
    'Welcome to Innotech Medical Pvt Ltd. By accessing our website, purchasing our biomedical equipment, utilizing our clinical engineering services, or entering into distribution agreements with us, you agree to comply with and be bound by the following terms and conditions.',
  sections: [
    {
      id: 'acceptance',
      title: '1. Acceptance of Terms',
      content:
        'By accessing this website, requesting quotes, or procuring medical machinery, diagnostic systems, surgical disposables, and turnkey engineering solutions from Innotech Medical Pvt Ltd, you acknowledge that you have read, understood, and agreed to these Terms and Conditions in full compliance with relevant Pakistani healthcare regulations and DRAP (Drug Regulatory Authority of Pakistan) guidelines.',
    },
    {
      id: 'equipment-quotes',
      title: '2. Equipment Quotations & Orders',
      content:
        'All formal quotations issued for medical equipment, laboratory diagnostic analyzers, and surgical disposables are subject to principal availability, currency fluctuation adjustments, and official written confirmation. Purchase orders placed by hospitals, clinical laboratories, or distribution partners become binding upon written confirmation from Innotech Medical Pvt Ltd.',
    },
    {
      id: 'installation-warranty',
      title: '3. Turnkey Installation, Warranty & Calibration',
      content:
        'All biomedical devices distributed by Innotech Medical Pvt Ltd are installed, tested, and calibrated by qualified biomedical engineers. Warranty coverage covers manufacturer defects as stipulated in the formal contract. Unauthorized repairs, tampering by uncertified personnel, or improper electrical/environmental site conditions shall void the warranty coverage.',
    },
    {
      id: 'maintenance-sla',
      title: '4. Service Level Agreements & 24/7 Emergency Support',
      content:
        'Emergency technical support, scheduled preventive maintenance, and spare parts supply are provided according to the executed Service Level Agreement (SLA). Emergency dispatch turnaround times apply to designated critical care units, ICUs, and surgical suites under active service contracts.',
    },
    {
      id: 'limitation-liability',
      title: '5. Limitation of Clinical Liability',
      content:
        'Innotech Medical Pvt Ltd shall not be liable for any indirect, incidental, or consequential damages resulting from improper equipment operation, unapproved clinical application, or failure to follow operator training instructions provided during official equipment handover.',
    },
    {
      id: 'governing-law',
      title: '6. Governing Law & Jurisdiction',
      content:
        'These terms and conditions are governed by and construed in accordance with the laws of the Islamic Republic of Pakistan. Any legal disputes arising in connection with these terms shall be subject to the exclusive jurisdiction of the competent courts in Karachi, Sindh, Pakistan.',
    },
  ],
  contactEmail: 'info@innotecmedical.org',
  contactPhone: '+92 331 6699992',
  contactAddress: '1st Floor, Plot: A-301, Sardar Ali Sabri Road, Block-2, Gulshan e Iqbal, Karachi, Sindh, Pakistan.',
};

export const fallbackPrivacyPage = {
  banner: {
    enabled: true,
    title: 'Privacy Policy',
    subTitle: 'Your Data Protection & Confidentiality at Innotech Medical',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  lastUpdated: 'August 15, 2026',
  companyName: 'Innotech Medical Pvt Ltd',
  introduction:
    'Innotech Medical Pvt Ltd ("we", "our", or "us") is dedicated to protecting the privacy, confidentiality, and security of our healthcare partners, client hospitals, laboratories, clinicians, and website visitors across Pakistan.',
  sections: [
    {
      id: 'collection',
      title: '1. Information We Collect',
      content:
        'We collect institutional and contact information necessary to provide biomedical equipment distribution, technical maintenance, customer support, and clinical newsletter updates. This includes names, hospital/laboratory affiliations, professional email addresses, telephone numbers, shipping addresses, and equipment inquiry details.',
    },
    {
      id: 'use-of-info',
      title: '2. How We Use Your Information',
      content:
        'Your information is used strictly to process equipment procurement orders, dispatch biomedical engineers for on-site calibration, coordinate emergency maintenance, provide regulatory compliance documents, respond to live support inquiries, and send critical product updates.',
    },
    {
      id: 'data-protection',
      title: '3. Data Security & Confidentiality',
      content:
        'We implement industry-standard technical and organizational security protocols, including encrypted communications and secure server storage, to prevent unauthorized access, disclosure, alteration, or destruction of your institutional and personal information.',
    },
    {
      id: 'third-party',
      title: '4. Third-Party Sharing & Compliance',
      content:
        'Innotech Medical Pvt Ltd does not sell, lease, or trade your information to third parties. We share information only with authorized logistics providers, OEM principal manufacturers for warranty registrations, or regulatory authorities when mandated by Pakistani healthcare law.',
    },
    {
      id: 'cookies',
      title: '5. Cookies & Analytics',
      content:
        'Our website uses analytical cookies solely to monitor website traffic, enhance user browsing experience, and optimize our medical catalog presentation. You can manage or disable cookie preferences through your web browser settings.',
    },
    {
      id: 'your-rights',
      title: '6. Your Rights & Contact Information',
      content:
        'You have the right to request access to the personal data we hold about your facility, request corrections or updates, or request removal from our promotional and newsletter mailing lists at any time by contacting our support team.',
    },
  ],
  contactEmail: 'info@innotecmedical.org',
  contactPhone: '+92 331 6699992',
  contactAddress: '1st Floor, Plot: A-301, Sardar Ali Sabri Road, Block-2, Gulshan e Iqbal, Karachi, Sindh, Pakistan.',
};

export const fallbackServicesPage = {
  banner: {
    enabled: true,
    title: 'Services- 01',
    subTitle: 'Bioxlab : Services',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  servicesSection: {
    enabled: true,
    subTitle: 'our Services',
    title: 'Service Area',
    bgImage: '/assets/img/shape/shape-bg-01.png',
    items: [
      {
        id: 'srv-1',
        title: 'Hemoglobin Test',
        slug: 'hemoglobin-test',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-hemoglobin-test-meter',
        iconTheme: 'default',
        btnText: 'Read More',
        link: '/services/hemoglobin-test',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Automated Clinical Diagnostic & Hematology Systems',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Hemoglobin & Hematology Analytical Process',
        processText: 'Innotech Medical supplies automated multi-parameter hematology analyzers that provide rapid, dependable complete blood count (CBC) profiles and accurate hemoglobin diagnostics for modern clinical laboratories and hospital pathology departments across Pakistan.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
        processPoints: [
          'Precision microfluidic measurement channels with laser optical flow cytometry.',
          'High-throughput automated sampling with closed-tube barcode scanning.',
          'Fully compliant with ISO 15189 laboratory quality standards.',
          'Comprehensive warranty, preventive calibration, and genuine reagent packs.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Our turnkey analytical process guarantees maximum instrument uptime, precision calibration benchmarks, and seamless hospital LIS (Laboratory Information System) integration.',
        stepsCol1: ['Sample Preparation & Barcode Scan', 'Microfluidic Analysis', 'Automated Quality Control', 'In aliquet dui nec lectus'],
        stepsCol2: ['High-Resolution Optical Detection', 'Digital Differential Profiling', 'Real-Time LIS Sync', 'Bacteria Markers'],
        stepsCol3: ['Automated Probe Washing', 'Diagnostic Report Generation', 'Preventive Maintenance Log', 'Extramural Funding'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
      {
        id: 'srv-2',
        title: 'Blood Testing',
        slug: 'blood-testing',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-blood-test',
        iconTheme: 'pink',
        btnText: 'Read More',
        link: '/services/blood-testing',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Automated Clinical Blood Analysis & Laboratory Diagnostics',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Blood Testing & Diagnostic Workflow Process',
        processText: 'Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system, and sed expounds the actual teachings of that greater truth.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
        processPoints: [
          'Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.',
          'Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque.',
          'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis.',
          'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        stepsCol1: ['Extramural Funding', 'Bacteria Markers', 'Nam nec mi euismod', 'In aliquet dui nec lectus'],
        stepsCol2: ['Sample Preparation', 'Optical Detection', 'Quality Control Verification', 'Automated Calibration'],
        stepsCol3: ['LIS Data Sync', 'Report Validation', 'Digital Archiving', 'Preventive Maintenance'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
      {
        id: 'srv-3',
        title: 'Biochemistry',
        slug: 'biochemistry',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-biochemistry',
        iconTheme: 'green',
        btnText: 'Read More',
        link: '/services/biochemistry',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Advanced Clinical Biochemistry & Immunoassay Systems',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Biochemistry Analytical Process',
        processText: 'Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a completed account of the system. Our clinical chemistry systems offer unmatched photometric precision.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.',
        processPoints: [
          'Discrete, random access, fully automated biochemistry systems.',
          'Holographic concave flat field grating optics with sub-nanometer accuracy.',
          'Direct refrigeration system for reagent trays ensuring extended reagent stability.',
          'Automated probe washing with carry-over less than 0.05%.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto.',
        stepsCol1: ['Extramural Funding', 'Bacteria Markers', 'Nam nec mi euismod', 'In aliquet dui nec lectus'],
        stepsCol2: ['Reagent Loading', 'Photometric Calibration', 'STAT Sample Prioritization', 'Automated Dilution'],
        stepsCol3: ['LIS Data Sync', 'Report Generation', 'Diagnostic Verification', 'Scheduled Maintenance'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
      {
        id: 'srv-4',
        title: 'Histopatology',
        slug: 'histopatology',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-dna-1',
        iconTheme: 'sky',
        btnText: 'Read More',
        link: '/services/histopatology',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Comprehensive Histology, Cytology & Tissue Processing Systems',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Histopathology Tissue Examination Process',
        processText: 'Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Innotech Medical supplies automated tissue processors.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.',
        processPoints: [
          'Precision rotary microtomes with micrometric sectioning thickness control.',
          'Automated vacuum tissue processors with enclosed fume control systems.',
          'High-throughput automated slide stainers and coverslippers.',
          'Cryostats for rapid intraoperative frozen section diagnostics.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.',
        stepsCol1: ['Tissue Fixation', 'Dehydration & Clearing', 'Paraffin Embedding', 'Precision Microtomy'],
        stepsCol2: ['Slide Mounting', 'Automated H&E Staining', 'Coverslipping', 'Quality Inspection'],
        stepsCol3: ['Digital Slide Scanning', 'Pathologist Review', 'Diagnostic Reporting', 'Specimen Archiving'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
      {
        id: 'srv-5',
        title: 'Microbioogy',
        slug: 'microbiology',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-bacteria',
        iconTheme: 'default',
        btnText: 'Read More',
        link: '/services/microbiology',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Automated Microbial Identification & Susceptibility Testing',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Microbiology Identification & AST Process',
        processText: 'Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Accelerate organism identification.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.',
        processPoints: [
          'Rapid microbial identification for Gram-negative, Gram-positive, and fungal pathogens.',
          'Automated minimum inhibitory concentration (MIC) determination.',
          'Continuous-monitoring blood culture incubation systems.',
          'Full compliance with EUCAST and CLSI antimicrobial testing guidelines.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.',
        stepsCol1: ['Inoculation & Incubation', 'Bacterial Isolation', 'ID Card Setup', 'Continuous Optical Reading'],
        stepsCol2: ['Phenotypic Analysis', 'Expert System Rule Check', 'MIC Validation', 'Resistance Flagging'],
        stepsCol3: ['LIS Real-Time Sync', 'Critical Result Notification', 'Epidemiology Tracking', 'Sterilization Control'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
      {
        id: 'srv-6',
        title: 'Genetics',
        slug: 'genetics',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor. Vivamus quis ex nulla.Nam eget dui vel quam',
        iconClass: 'flaticon-dna',
        iconTheme: 'pink',
        btnText: 'Read More',
        link: '/services/genetics',
        enabled: true,
        bannerImage: '/assets/img/banner/breadcrumb-01.jpg',
        bannerSubTitle: 'Advanced Molecular Diagnostics, PCR & Genetic Analysis',
        image1: '/assets/img/services/services-thumb-07.jpg',
        image2: '/assets/img/services/services-thumb-08.jpg',
        showcaseBanner: '/assets/img/services/services-thumb-09.jpg',
        processTitle: 'Genetic & Molecular Diagnostic Process',
        processText: 'Must explain to you how all this mistaken idea of denouncing works pleasure and praising its pain was born and I will gives you a itself completed account of the system. Our real-time PCR platforms deliver sub-single-copy sensitivity.',
        processText2: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.',
        processPoints: [
          'Multi-channel optical fluorescence detection (FAM, VIC, ROX, CY5, etc.).',
          'Automated high-speed magnetic bead nucleic acid extraction.',
          'Precision peltier thermal blocks with rapid ramp rates up to 6.5°C/sec.',
          'Intuitive software with absolute quantification and melting curve analysis.',
        ],
        stepsTitle: '4 Simple Steps',
        stepsText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.',
        stepsCol1: ['Automated DNA/RNA Extraction', 'PCR Master Mix Preparation', 'Optical Plate Loading', 'Thermal Cycling Run'],
        stepsCol2: ['Fluorescence Signal Acquisition', 'Threshold Baseline Calculation', 'Amplification Curve Review', 'Gene Mutation Check'],
        stepsCol3: ['Quality Control Approval', 'Diagnostic Report Export', 'LIS Integration', 'Instrument Decontamination'],
        researchTitle: 'Our Research',
        researchText: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
        bottomLinkText: 'Our Project',
        bottomLink: '/contact',
      },
    ],
  },
  chooseSection: {
    enabled: true,
    subTitle: 'Our Specialists',
    title: 'Why Choose Us',
    items: [
      {
        id: 'ch-1',
        title: 'High Quality Services',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor.',
        iconClass: 'flaticon-microscope',
        iconTheme: 'default',
        delay: '.2s',
        mlClass: 'ml-15',
      },
      {
        id: 'ch-2',
        title: 'Fast Working Process',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor.',
        iconClass: 'flaticon-thinking',
        iconTheme: 'pink',
        delay: '.4s',
        mlClass: 'ml-35',
      },
      {
        id: 'ch-3',
        title: '24/7 Customer Support',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor.',
        iconClass: 'flaticon-24-hours-1',
        iconTheme: 'green',
        delay: '.6s',
        mlClass: 'ml-55',
      },
      {
        id: 'ch-4',
        title: 'We have Expert Team',
        description: 'Nam eget dui vel quam sodales semper quis porttitor tortor.',
        iconClass: 'flaticon-team',
        iconTheme: 'sky',
        delay: '.8s',
        mlClass: 'ml-75',
      },
    ],
    bottomText: 'Laboratories Used For Scientific Research :',
    bottomLinkText: 'Take Many Forms',
    bottomLink: '/contact',
  },
  supportSection: {
    enabled: true,
    subTitle: 'Get in touch',
    title: 'Need Any Help',
    tagline: 'Derect Contact with us',
    btnText: 'Send Massage',
  },
};

export const fallbackResearchProjects = [
  {
    id: 1,
    title: 'Biomedical Diagnostic Accuracy in Critical Care',
    category: 'Diagnostic Systems',
    description: 'Evaluating advanced ultrasound doppler and clinical monitoring in high-acuity ICUs across Pakistan.',
    image: '/assets/img/research/research-thumb-01.jpg',
    enabled: true,
  },
  {
    id: 2,
    title: 'Operating Room Precision & Surgical Disposable Safety',
    category: 'Surgical Solutions',
    description: 'Ensuring zero-contamination and clinical reliability in laparoscopic surgical procedures.',
    image: '/assets/img/research/research-thumb-02.jpg',
    enabled: true,
  },
  {
    id: 3,
    title: 'Next-Generation Hemoglobin & Blood Gas Diagnostics',
    category: 'Hematology & Lab',
    description: 'High-throughput automated laboratory diagnostics delivering sub-minute clinical reports.',
    image: '/assets/img/research/research-thumb-03.jpg',
    enabled: true,
  },
  {
    id: 4,
    title: 'Hospital Turnkey Engineering & Cleanroom Standards',
    category: 'Turnkey Solutions',
    description: 'Complete site architecture, HVAC filtration, and medical gas pipeline deployment for hospitals.',
    image: '/assets/img/research/research-thumb-04.jpg',
    enabled: true,
  },
  {
    id: 5,
    title: 'AI-Enhanced Medical Imaging & Radiodiagnostics',
    category: 'Radiology',
    description: 'Integrating digital radiography and high-resolution imaging for early disease detection.',
    image: '/assets/img/research/research-thumb-05.jpg',
    enabled: true,
  },
  {
    id: 6,
    title: 'Advanced Neonatal Care & Biosafety Incubators',
    category: 'Pediatric Care',
    description: 'Micro-climate controlled neonatal incubators engineered for preterm infant stability.',
    image: '/assets/img/research/research-thumb-06.jpg',
    enabled: true,
  },
];

export const fallbackResearchPage = {
  banner: {
    enabled: true,
    title: 'Biomedical Research & Projects',
    subTitle: 'Advancing Clinical Science and Healthcare Innovations',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  items: fallbackResearchProjects,
};

export const fallbackBlogList = [
  {
    _id: 'blog-1',
    slug: 'advances-in-biomedical-imaging-and-diagnostics',
    title: 'Advances in Biomedical Imaging & Precision Diagnostics in Pakistan',
    category: 'Biomedical Engineering',
    author: 'Innotech Editorial Team',
    dateDay: '12',
    dateMonth: 'Aug',
    dateYear: '2026',
    views: '1,840',
    image: '/assets/img/blog/blog-in-01.jpg',
    excerpt: 'Modern healthcare facilities in Pakistan are rapidly transitioning towards high-resolution digital imaging and automated diagnostics for faster, error-free clinical outcomes.',
    content: `Biomedical engineering has undergone revolutionary advancements over the past decade. High-resolution ultrasound systems, advanced digital radiography, and automated clinical analyzers have significantly improved diagnostic speed and precision.

At Innotech Medical Pvt Ltd, our commitment is to bridge the gap between global medical innovators and healthcare institutions in Pakistan. By delivering state-of-the-art diagnostic instruments, we empower clinicians to make life-saving decisions with confidence.

Key Technological Highlights:
- Real-time digital signal processing in ultrasound Doppler.
- Sub-minute blood gas and electrolyte analyzers for critical care units.
- Turnkey clinical deployment with full OEM calibration and 24/7 engineering backup.`,
    tags: ['Biomedical', 'Diagnostics', 'Medical Imaging', 'Healthcare'],
    socialLinks: {
      linkedin: 'https://www.linkedin.com/company/innotech-medical',
      twitter: 'https://twitter.com/innotechmedical',
      facebook: 'https://facebook.com/innotechmedical',
    },
    enabled: true,
  },
  {
    _id: 'blog-2',
    slug: 'turnkey-hospital-projects-and-icu-equipment',
    title: 'Key Considerations for Turnkey Hospital & ICU Equipment Integration',
    category: 'Turnkey Healthcare',
    author: 'Engr. Faisal Malik',
    dateDay: '08',
    dateMonth: 'Aug',
    dateYear: '2026',
    views: '2,150',
    image: '/assets/img/blog/blog-in-02.jpg',
    excerpt: 'Building modern intensive care units requires seamless coordination between medical gas architecture, patient monitoring networks, and sterile surgical environments.',
    content: `Developing a modern hospital or upgrading an Intensive Care Unit (ICU) requires more than just purchasing equipment. It demands holistic architectural engineering, reliable medical gas distribution, uninterruptible power redundancy, and precision calibration.

Innotech Medical specializes in turnkey healthcare projects, handling everything from initial architectural feasibility and equipment selection to physical deployment, site testing, and staff clinical training.`,
    tags: ['Turnkey ICU', 'Engineering', 'Hospitals', 'Pakistan'],
    socialLinks: {
      linkedin: 'https://www.linkedin.com/company/innotech-medical',
      twitter: 'https://twitter.com/innotechmedical',
      facebook: 'https://facebook.com/innotechmedical',
    },
    enabled: true,
  },
  {
    _id: 'blog-3',
    slug: 'preventive-maintenance-and-biomedical-calibration',
    title: 'Why Preventive Maintenance & Precision Calibration Save Patient Lives',
    category: 'Technical Support',
    author: 'Engr. Sarah Ahmed',
    dateDay: '02',
    dateMonth: 'Aug',
    dateYear: '2026',
    views: '1,420',
    image: '/assets/img/blog/blog-in-03.jpg',
    excerpt: 'Regular biomedical calibration prevents critical diagnostic drift and ensures zero unexpected downtime in life-support and emergency care equipment.',
    content: `In critical healthcare environments, equipment failure is not an option. Routine biomedical calibration and preventive maintenance are essential to ensure patient monitors, ventilators, and surgical systems perform at peak accuracy.

Our dedicated 24/7 technical dispatch team at Innotech Medical provides scheduled servicing, OEM spare parts replacement, and emergency troubleshooting across healthcare facilities nationwide.`,
    tags: ['Maintenance', 'Calibration', 'Biomedical Support'],
    socialLinks: {
      linkedin: 'https://www.linkedin.com/company/innotech-medical',
      twitter: 'https://twitter.com/innotechmedical',
      facebook: 'https://facebook.com/innotechmedical',
    },
    enabled: true,
  },
];

export const fallbackInquiries = [
  {
    _id: 'inq-101',
    source: 'Contact Page',
    name: 'Dr. Tariq Mahmood',
    email: 'tariq.mahmood@shifa-hospital.pk',
    phone: '+92 300 8549120',
    subject: 'ICU Ventilators & Monitoring System Quotation',
    message:
      'We are upgrading our 12-bed surgical ICU ward in Islamabad and require a formal quotation and compliance specification sheet for your high-frequency ventilators and multi-parameter monitors.',
    status: 'unread',
    replies: [],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'inq-102',
    source: 'Home Page Consultation',
    name: 'Ayesha Siddiqui (Procurement Lead)',
    email: 'procurement@al-shifa-diagnostics.com',
    phone: '+92 333 4210987',
    subject: 'Automated Clinical Chemistry Analyzer',
    message:
      'Looking for turnkey installation of automated blood biochemistry analyzers and annual maintenance contract details.',
    status: 'unread',
    replies: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'inq-103',
    source: 'Contact Page',
    name: 'Engr. Salman Raza',
    email: 'salman.raza@khi-medtech.org',
    phone: '+92 321 9988771',
    subject: 'Ultrasound Machine Calibration & Repair Service',
    message:
      'Need urgent on-site calibration and probe replacement for color Doppler ultrasound unit in Karachi.',
    status: 'replied',
    replies: [
      {
        id: 'rep-1',
        subject: 'Re: Ultrasound Machine Calibration & Repair Service',
        message:
          'Dear Engr. Salman, our biomedical field engineer has been dispatched to your facility. Please find technician contact details attached.',
        sentBy: 'Innotech Engineering Desk',
        sentTo: 'salman.raza@khi-medtech.org',
        sentAt: new Date(Date.now() - 43200000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];


export const fallbackBlogPage = {
  banner: {
    enabled: true,
    title: 'Articles, News & Clinical Insights',
    subTitle: 'Stay Updated with Latest Trends in Medical Technology',
    bgImage: '/assets/img/banner/breadcrumb-01.jpg',
  },
  items: fallbackBlogList,
};

export const fallbackComments = [
  {
    _id: 'com-101',
    blogSlug: 'advances-in-biomedical-imaging-and-diagnostics',
    blogTitle: 'Advances in Biomedical Imaging & Precision Diagnostics in Pakistan',
    name: 'Dr. Zeeshan Ali',
    email: 'zeeshan.ali@cardio-centre.pk',
    comment:
      'Very informative overview. Digital imaging upgrades and precision ultrasound calibration are indeed critical for early diagnosis in emergency cardiac care.',
    status: 'approved',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'com-102',
    blogSlug: 'turnkey-hospital-projects-and-icu-equipment',
    blogTitle: 'Key Considerations for Turnkey Hospital & ICU Equipment Integration',
    name: 'Engr. Kamran Siddiqui',
    email: 'kamran.engr@healthtech.com',
    comment:
      'Turnkey solutions save hospital management months of vendor coordination. Excellent points on medical gas pipeline calibration and HVAC cleanrooms.',
    status: 'approved',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const fallbackSubscribers = [
  {
    _id: 'sub-1',
    email: 'procurement@shifa-hospital.pk',
    source: 'Footer Newsletter',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'sub-2',
    email: 'biomedical.lead@dow-health.org',
    source: 'Header Sidebar',
    status: 'active',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: 'sub-3',
    email: 'tariq.mahmood@khi-medtech.org',
    source: 'Footer Newsletter',
    status: 'active',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const fallbackAnalytics = {
  pageViews: [
    {
      visitorId: 'v_user_1',
      path: '/',
      pageTitle: 'Home - Innotech Medical Systems',
      duration: 165,
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      visitorId: 'v_user_2',
      path: '/blog/advances-in-biomedical-imaging-and-diagnostics',
      pageTitle: 'Advances in Biomedical Imaging & Precision Diagnostics in Pakistan',
      duration: 240,
      isBlog: true,
      blogSlug: 'advances-in-biomedical-imaging-and-diagnostics',
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      visitorId: 'v_user_3',
      path: '/services',
      pageTitle: 'Turnkey Hospital & Biomedical Services',
      duration: 195,
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 5400000).toISOString(),
    },
    {
      visitorId: 'v_user_4',
      path: '/contact',
      pageTitle: 'Contact Us - Clinical Equipment Support',
      duration: 120,
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      visitorId: 'v_user_5',
      path: '/about',
      pageTitle: 'About Innotech Medical Pvt Ltd',
      duration: 150,
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 9000000).toISOString(),
    },
    {
      visitorId: 'v_user_6',
      path: '/blog/turnkey-hospital-projects-and-icu-equipment',
      pageTitle: 'Key Considerations for Turnkey Hospital & ICU Equipment Integration',
      duration: 215,
      isBlog: true,
      blogSlug: 'turnkey-hospital-projects-and-icu-equipment',
      date: new Date().toISOString().split('T')[0],
      createdAt: new Date(Date.now() - 10800000).toISOString(),
    },
  ],
  uniqueBlogViews: {
    'advances-in-biomedical-imaging-and-diagnostics': ['v_user_2'],
    'turnkey-hospital-projects-and-icu-equipment': ['v_user_6'],
  },
};



